OnlineBanking/Controllers/AccountController.cs
using OnlineBanking.Data.Repositories;
using OnlineBanking.Data.Services;
using OnlineBanking.Data.Services.Database;
using OnlineBanking.Data.ViewModels.AuthenticationViewModels;
using System.Web.Helpers;
using System.Web.Mvc;

namespace OnlineBanking.Controllers
{
    [Authorize]
    public class AccountController : Controller
    {
        private AuthenticationService _authenticationService;
        private PaymentService _paymentService;

        public AccountController()
        {
            _authenticationService = new AuthenticationService();
            _paymentService = new PaymentService();
        }

        [Route("account/dashboard")]
        public ActionResult Index()
        {
            var repo = new CustomerRepository();

            //var customer = repo.GetCustomerByAccountNo(20802074);

            return View();
        }

        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterViewModel model)
        {
            var data = new UserDatabaseService();

            if (ModelState.IsValid)
            {
                var result = data.CreateCustomer(model);

                if (result == true)
                {
                    return RedirectToAction("login", new { application = "success" });
                }
            }

            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Login(string application)
        {
            if (!string.IsNullOrEmpty(application))
            {
                ViewBag.Message = "applicationsuccess";
            }

            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var authenticated = _authenticationService.LoginCustomer(model);

                if (authenticated)
                {
                    return RedirectToAction("index");
                }

            }

            return View(model);
        }

        public ActionResult CurrentAccount()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ProcessPayment()
        {
            return View();
        }

        public ActionResult Messages()
        {
            return View();
        }

        public ActionResult Transactions(string accountId)
        {
            return View();
        }

        public ActionResult Settings()
        {
            return View();
        }

        [AllowAnonymous]
        [Route("account/help-center")]
        public ActionResult HelpCenter()
        {
            var customerId = User.Identity.Name;

            return Content(customerId);
        }

        public ActionResult Logout()
        {
            _authenticationService.Logout();

            return RedirectToAction("login");
        }
    }
}

OnlineBanking/Controllers/GlobalController.cs
using OnlineBanking.Data.Services;
using System.Web.Mvc;

namespace OnlineBanking.Controllers
{
    public class GlobalController : Controller
    {
        private CustomerService _customerService;

        public GlobalController()
        {
            _customerService = new CustomerService();
        }

        [ChildActionOnly]
        public PartialViewResult Navigation()
        {
            var model = _customerService.InitialiseCustomerDetailsViewModel();

            return PartialView("_Navigation", model);
        }
    }
}

OnlineBanking/Controllers/HomeController.cs
using OnlineBanking.Data.Services;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace OnlineBanking.Controllers
{
    public class HomeController : Controller
    {
        private HomeService _homeService;

        public HomeController()
        {
            _homeService = new HomeService();
        }

        public async Task<ActionResult> Index()
        {
            var model = await _homeService.InitialiseHomeViewModel();

            return View(model);
        }

        [Route("about")]
        public ActionResult About()
        {
            return View();
        }

        [Route("contact")]
        public ActionResult Contact()
        {
            return View();
        }
    }
}

OnlineBanking/Controllers/LoanController.cs
using System.Web.Mvc;

namespace OnlineBanking.Controllers
{
    public class LoanController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Apply()
        {
            return View();
        }
    }
}

OnlineBanking/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<div id="about-page">
    <h2 class="page-heading">About Online Banking Web Project</h2>
</div>

OnlineBanking/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineBanking/Views/Home/Index.cshtml
@model OnlineBanking.Data.ViewModels.HomeViewModel

@{
    ViewBag.Title = "Home";
}

<div id="home-page">
    <section class="header main-hero-image">
        <div class="main-hero-text">
            <h1 class="hero-heading">Apply for an Online Banking account today</h1>
            <p>Safe and secure banking from your home</p>
            <div class="spacer"></div>
            <a href="/account/register" class="btn btn-main"><i class="fa-solid fa-arrow-right-to-bracket"></i> Register</a>
        </div>
    </section>

    <section class="products-section">
        <div class="row">
            <div class="col-md-4">
                <div class="product-item">
                    <h4>Current Accounts</h4>
                    <i class="fa-solid fa-sterling-sign"></i>
                    <div class="spacer"></div>
                    <p>Apply for a current account with many benefits and rewards</p>
                    <a href="/account/register" class="btn btn-main">Find out more</a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="product-item">
                    <h4>Credit Accounts</h4>
                    <i class="fa-solid fa-credit-card"></i>
                    <div class="spacer"></div>
                    <p>Apply for a credit card at low interest rate of %19.00 APR</p>
                    <a href="/account/register" class="btn btn-main">Find out more</a>
                </div>
            </div>
            <div class="col-md-4">
                <div class="product-item">
                    <h4>Saving Accounts</h4>
                    <i class="fa-solid fa-piggy-bank"></i>
                    <div class="spacer"></div>
                    <p>Apply for a savings account and save your money at no cost</p>
                    <a href="/account/register" class="btn btn-main">Find out more</a>
                </div>
            </div>
        </div>
    </section>

    <section class="confidence-hero-image">
        <div class="confidence-hero-text">
            <h1 class="hero-heading">Safe and secure banking from your home</h1>
            <p>An easy and secure way to bank how you want, where you want and when you want.</p>
            <p>It makes managing your money simpler.</p>
            <div class="spacer"></div>
            <a href="/account/login" class="btn btn-main"><i class="fa-solid fa-lock"></i> Login Securely</a>
        </div>
    </section>

    <div class="news-section">
        <div class="row">
            <div class="col-md-8">
                <section class="information-container">
                    <h4>Latest News</h4>

                    @if (Model.IsNewsDisplayed)
                    {
                        foreach (var article in Model.NewsResults.Take(5))
                        {
                            <div class="spacer"></div>
                            <a href="@article.link" target="_blank" class="main-link"><i class="fa-solid fa-arrow-up-right-from-square"></i> @article.title</a>
                        }
                    }
                    else
                    {
                        <div class="spacer"></div>
                        <a href="https://www.globenewswire.com/news-release/2022/03/15/2403124/19499/en/Matrix-PDM-Engineering-Awarded-EPC-for-Expansion-of-Natural-Gas-Processing-Facility-to-Double-Existing-Facility-Capacity.html" target="_blank" class="main-link"><i class="fa-solid fa-arrow-up-right-from-square"></i> Matrix PDM Engineering Awarded EPC for Expansion of Natural Gas Processing Facility to Double Existing Facility Capacity</a>
                        <div class="spacer"></div>
                        <a href="https://www.fool.com/investing/2022/03/15/novavax-is-betting-its-covid-vaccine-will-win-us-a/?source=iedfolrf0000001" target="_blank" class="main-link"><i class="fa-solid fa-arrow-up-right-from-square"></i> Novavax Is Betting Its COVID Vaccine Will Win U.S. Authorization. Should You?</a>
                        <div class="spacer"></div>
                        <a href="https://www.fool.com/investing/2022/03/15/why-crypto-investors-yawned-at-amcs-early-adoption/?source=iedfolrf0000001" target="_blank" class="main-link"><i class="fa-solid fa-arrow-up-right-from-square"></i> Why Crypto Investors Yawned at AMC&#39;s Early Adoption of Dogecoin and Shiba Inu</a>
                        <div class="spacer"></div>
                        <a href="https://www.carandbike.com/news/ford-to-introduce-3-new-evs-and-4-new-electric-cvs-in-europe-by-2024-2823934?publisher=newsstand&amp;amp;utm_source=googlenews" target="_blank" class="main-link"><i class="fa-solid fa-arrow-up-right-from-square"></i> Ford To Introduce 3 New EVs And 4 New Electric CVs In Europe By 2024</a>
                        <div class="spacer"></div>
                        <a href="https://www.fool.com/investing/2022/03/15/warren-buffett-gained-182-billion-these-4-stocks/?source=iedfolrf0000001" target="_blank" class="main-link"><i class="fa-solid fa-arrow-up-right-from-square"></i> Warren Buffett Has Gained Over $182 Billion On These 4 Stocks</a>
                    }
                </section>
            </div>
            <div class="col-md-4">
                <section class="information-container">
                    <h4>Latest Exchange Rates</h4>
                    <div class="spacer"></div>
                    <div class="exchange-rates-list">
                        <p class="exchange-rate-text"><i class="fa-solid fa-coins"></i> GBP - EUR - </p>
                        <p class="exchange-rate-text"><i class="fa-solid fa-coins"></i> GBP - USD - </p>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <section class="loan-hero-image">
        <div class="loan-hero-text">
            <h1 class="hero-heading">Let us take the stress out of borrowing money</h1>
            <p>Apply for a loan between £1,000 and £10,000</p>
            <p>Representative 3.4% APR</p>
            <div class="spacer"></div>
            <a href="/loan/apply" class="btn btn-main"><i class="fa-solid fa-arrow-right-to-bracket"></i> Apply Today</a>
        </div>
    </section>

</div>

OnlineBanking/Views/Loan/Apply.cshtml
@{
    ViewBag.Title = "Apply";
}

<div id="loan-apply-page">
    <h2 class="page-heading">Apply for Loan</h2>
</div>

OnlineBanking/Views/Shared/_Footer.cshtml
<div class="container">
    <div class="footer-content">
        <div class="row">
            <div class="col-md-4">
                <h5>About Online Banking</h5>
                <hr />
                <ul>
                    <li><a href="/account/about">About</a></li>
                    <li>@Html.ActionLink("About", "about", "account", new { }, null)</li>
                    <li>News</li>
                    <li><a href="/account/register">Register</a></li>
                    <li><a href="/account/login">Login</a></li>
                </ul>
            </div>
            <div class="col-md-4">
                <h5>Products & Services</h5>
                <hr />
                <ul>
                    <li>Current Accounts</li>
                    <li><a href="/account/loans">Loans</a></li>
                    <li>Saving Accounts</li>
                    <li>Credit Cards</li>
                </ul>
            </div>
            <div class="col-md-4">
                <h5>Get In Touch</h5>
                <hr />
                <ul>
                    <li>Contact</li>
                    <li>Mobile Banking</li>
                    <li>Careers</li>
                    <li>Test Accounts</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <hr />
        <div class="ft">
            <p>Developed by JO</p>
            <div class="footer-icons">
                <i class="fa-brands fa-facebook"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-linkedin"></i>
                <i class="fa-brands fa-youtube"></i>
            </div>
        </div>
    </div>
</div>

OnlineBanking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Banking - @ViewBag.Title</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    @Styles.Render("~/css/css")
    @RenderSection("Styles", required: false)
    <script src="https://kit.fontawesome.com/6816c2b35b.js" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav>
        @Html.Action("Navigation", "Global")
    </nav>
    <div class="container">
        <div class="main">
            @RenderBody()
        </div>
    </div>

    <footer>
        @Html.Partial("_Footer")
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

OnlineBanking/Views/Shared/_Navigation.cshtml
@model OnlineBanking.Data.ViewModels.AccountViewModels.CustomerDetailsViewModel

@if(User.Identity.IsAuthenticated)
{
    <div class="account-topbar">
        <div class="container">
            <div class="account-topbar-content">
                <div id="name-account-section">
                    <p class="account-topbar-name-title">Welcome back, Jeremy!</p>
                    <small class="last-logged-in-date-text">Last Logged In: @Model.CustomerLogin.LastLoggedIn</small>
                </div>
                <div id="links-account-section">
                    <ul>
                        <li><a href="/account/messages">Messages</a></li>
                        <span class="account-topbar-link-divider">|</span>
                        <li><a href="/account/dashboard">Accounts</a></li>
                        <span class="account-topbar-link-divider">|</span>
                        <li><a href="/account/transactions">Transactions</a></li>
                        <span class="account-topbar-link-divider">|</span>
                        <li><a href="/account/settings">Settings</a></li>
                        <span class="account-topbar-link-divider">|</span>
                        <li><a href="/account/help-center">Help Center</a></li>
                        <span class="account-topbar-link-divider">|</span>
                        <li><a href="/account/logout">Logout</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
}

<div class="navbar main-background-color">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Online Banking", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/about">About</a></li>
                <li><a href="/news">News</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Current Accounts <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Apply New Current Account</a></li>
                        <li><a href="#">Basic Current Account</a></li>
                        <li><a href="#">Ultimate Current Account</a></li>
                        <li><a href="#">Current Account Help</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Credit Accounts <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Apply New Current Account</a></li>
                        <li><a href="#">Basic Current Account</a></li>
                        <li><a href="#">Ultimate Current Account</a></li>
                        <li><a href="#">Current Account Help</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Loans <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Apply New Loan</a></li>
                        <li><a href="#">Loans Home</a></li>
                        <li><a href="#">Loans Help</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Savings <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Basic Current Account</a></li>
                        <li><a href="#">Ultimate Current Account</a></li>
                    </ul>
                </li>
                <li><a href="/contact">Contact</a></li>
                <li><a href="/account/help-center">Help</a></li>
                @if (!User.Identity.IsAuthenticated)
                {
                    <li><a href="/account/login">Login</a></li>
                }
                else
                {
                    <li><a href="/account/logout">Logout</a></li>
                }
            </ul>
        </div>
    </div>
</div>